"""Initial schema

Revision ID: 2bca2962aa83
Revises: 
Create Date: 2026-08-09 16:01:43.955438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bca2962aa83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('super_admin', 'admin', name='adminrole'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'disabled', name='accountstatus'), nullable=False),
    sa.Column('invite_token_hash', sa.String(), nullable=True),
    sa.Column('invite_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classtype', sa.Enum('first_class', 'economy', 'intra_wilaya', name='classtype'), nullable=True),
    sa.Column('Rate_Per_Km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Wilaya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('wilaya_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wilaya_id'], ['Wilaya.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('working', 'not_working', name='tripstatus'), nullable=False),
    sa.Column('tripType', sa.Enum('inter_Wilaya', 'intra_Wilaya', name='triptype'), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['Line.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['Train.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['Line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Line_Station',
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['Line.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['Station.id'], ),
    sa.PrimaryKeyConstraint('line_id', 'station_id')
    )
    op.create_table('Notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['Line.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['Station.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['Trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Scheduler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['Station.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['Trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Vehicle_postion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('Longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['Trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vehicle_postion')
    op.drop_table('Scheduler')
    op.drop_table('Notice')
    op.drop_table('Line_Station')
    op.drop_table('line_geometry')
    op.drop_table('Trip')
    op.drop_table('Station')
    op.drop_table('Wilaya')
    op.drop_table('Train')
    op.drop_table('Ticket')
    op.drop_table('Line')
    op.drop_table('Admin')
    # ### end Alembic commands ###
