"""add role to admin

Revision ID: 7c73cdbda1b4
Revises: f58f683250ee
Create Date: 2026-07-30 16:44:27.929606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c73cdbda1b4'
down_revision: Union[str, Sequence[str], None] = 'f58f683250ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admin', sa.Column('role', sa.Enum('super_admin', 'admin', name='adminrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Admin', 'role')
    # ### end Alembic commands ###
