"""add columns to admin table

Revision ID: be18ed402e3f
Revises: 7c73cdbda1b4
Create Date: 2026-07-30 20:38:05.358735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be18ed402e3f'
down_revision: Union[str, Sequence[str], None] = '7c73cdbda1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Admin', sa.Column('email', sa.String(), nullable=False))
    op.add_column('Admin', sa.Column('status', sa.Enum('pending', 'active', 'disabled', name='accountstatus'), nullable=False))
    op.add_column('Admin', sa.Column('invite_token_hash', sa.String(), nullable=True))
    op.add_column('Admin', sa.Column('invite_token_expires_at', sa.DateTime(), nullable=True))
    op.alter_column('Admin', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'Admin', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Admin', type_='unique')
    op.alter_column('Admin', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Admin', 'invite_token_expires_at')
    op.drop_column('Admin', 'invite_token_hash')
    op.drop_column('Admin', 'status')
    op.drop_column('Admin', 'email')
    # ### end Alembic commands ###
