"""changed Longitude -> longitude 

Revision ID: e3b4ff724cb4
Revises: 437a39018380
Create Date: 2026-07-29 16:16:36.430724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b4ff724cb4'
down_revision: Union[str, Sequence[str], None] = '437a39018380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Station', sa.Column('longitude', sa.Float(), nullable=False))
    op.drop_column('Station', 'Longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Station', sa.Column('Longitude', sa.FLOAT(), nullable=False))
    op.drop_column('Station', 'longitude')
    # ### end Alembic commands ###
